
networks:
  databse:
  backend:

services:
  frontend:
    build:
      dockerfile: infrastructure/dev/dockerfiles/std.node.Dockerfile
      context: ../..
      args:
        SERVICE_PATH: ./frontend
    volumes:
      - ../../frontend:/usr/src/server
    ports:
      - '3002:3000'
    networks:
      - backend

  gateway:
    build:
      dockerfile: infrastructure/dev/dockerfiles/std.node.Dockerfile
      context: ../..
      args:
        SERVICE_PATH: ./gateway
    volumes:
      - ../../gateway:/usr/src/server
    ports:
      - '3001:3000'
    networks:
      - backend

  backend:
    build:
      dockerfile: infrastructure/dev/dockerfiles/std.node.Dockerfile
      context: ../..
      args:
        SERVICE_PATH: ./backend/HappyMushroomDragon
    volumes:
      - ../../backend/HappyMushroomDragon:/usr/src/server
    ports:
      - '3000:3000'
    networks:
      - backend
      - databse

  sql_server:
    image: mcr.microsoft.com/mssql/server
    container_name: sql_server_container
    restart: always
    env_file:
      - dev.env
    ports:
      - "5533:1433"
    networks:
      - databse
    volumes:
      - "./data:/var/opt/mssql/data"