
networks:
  backend:
  sql_server:

services:
  gateway:
    build:
      dockerfile: infrastructure/dev/dockerfiles/std.node.Dockerfile
      context: ../..
      args:
        SERVICE_PATH: ./gateway
    volumes:
      - ../../gateway:/usr/src/server
    ports:
      - '3001:3001'
    networks:
      - backend

  backend:
    build:
      dockerfile: infrastructure/dev/dockerfiles/std.node.Dockerfile
      context: ../..
      args:
        SERVICE_PATH: ./backend/HappyMushroomDragon
    volumes:
      - ../../backend/HappyMushroomDragon:/usr/src/server
    networks:
      - backend
      - sql_server

  sql_server:
    image: mcr.microsoft.com/mssql/server
    container_name: sql_server_container
    restart: always
    env_file:
      - dev.env
    ports:
      - "5533:1433"
    networks:
      - sql_server
    volumes:
      - "./data:/var/opt/mssql/data"